/*
 * Study Hub folders.
 * To link a card to its own Drive folder, add  drive: 'https://drive.google.com/drive/folders/...'
 * Cards without `drive` fall back to MATHRIX_CONFIG.driveRoot.
 * resources: any of 'notes', 'pdf', 'worksheet'.
 */
window.MATHRIX_STUDY = [
  /* ---------- Grade 10: Math ---------- */
  { grade: '10', subject: 'math', topic: 'Algebra', title: 'Quadratics and the discriminant',
    summary: 'Solve by factoring, completing the square and the formula, then read the roots from the graph.',
    resources: ['notes', 'pdf', 'worksheet'] },
  { grade: '10', subject: 'math', topic: 'Algebra', title: 'Polynomials and factoring',
    summary: 'Expand, factor and divide polynomials, and use the remainder theorem.',
    resources: ['notes', 'worksheet'] },
  { grade: '10', subject: 'math', topic: 'Algebra', title: 'Systems of equations',
    summary: 'Substitution, elimination and graphical solutions, with word problems.',
    resources: ['notes', 'pdf', 'worksheet'] },
  { grade: '10', subject: 'math', topic: 'Geometry', title: 'Circle theorems',
    summary: 'Angles in a circle, tangents and cyclic quadrilaterals, with proof practice.',
    resources: ['notes', 'pdf'] },
  { grade: '10', subject: 'math', topic: 'Geometry', title: 'Trigonometry in right triangles',
    summary: 'Sine, cosine and tangent for heights, distances and bearings.',
    resources: ['notes', 'worksheet'] },
  { grade: '10', subject: 'math', topic: 'Geometry', title: 'Coordinate geometry',
    summary: 'Distance, midpoint, gradient and equations of lines.',
    resources: ['notes', 'pdf', 'worksheet'] },
  { grade: '10', subject: 'math', topic: 'Calculus basics', title: 'Rates of change',
    summary: 'Average and instantaneous rate of change, and a first look at limits.',
    resources: ['notes', 'pdf'] },

  /* ---------- Grade 10: Mechanics ---------- */
  { grade: '10', subject: 'mechanics', topic: 'Kinematics', title: 'Motion graphs',
    summary: 'Read and sketch position-time and velocity-time graphs, and know what slope and area mean.',
    resources: ['notes', 'pdf', 'worksheet'] },
  { grade: '10', subject: 'mechanics', topic: 'Kinematics', title: 'Equations of motion',
    summary: 'Constant-acceleration problems with the five kinematic equations.',
    resources: ['notes', 'worksheet'] },
  { grade: '10', subject: 'mechanics', topic: 'Statics', title: 'Forces and free-body diagrams',
    summary: 'Name every force on an object and draw the diagram before you calculate.',
    resources: ['notes', 'pdf'] },
  { grade: '10', subject: 'mechanics', topic: 'Statics', title: 'Equilibrium of a particle',
    summary: 'Resolve forces into components and solve for tension and reaction forces.',
    resources: ['notes', 'worksheet'] },
  { grade: '10', subject: 'mechanics', topic: 'Dynamics', title: "Newton's three laws",
    summary: 'Link net force, mass and acceleration, and spot action-reaction pairs.',
    resources: ['notes', 'pdf', 'worksheet'] },
  { grade: '10', subject: 'mechanics', topic: 'Dynamics', title: 'Friction and inclined planes',
    summary: 'Static and kinetic friction, and motion up and down a slope.',
    resources: ['notes', 'worksheet'] },

  /* ---------- Grade 11: Math ---------- */
  { grade: '11', subject: 'math', topic: 'Algebra', title: 'Functions and transformations',
    summary: 'Domain, range, composition and inverses, plus shifts, stretches and reflections of graphs.',
    resources: ['notes', 'pdf', 'worksheet'] },
  { grade: '11', subject: 'math', topic: 'Algebra', title: 'Exponentials and logarithms',
    summary: 'Laws of logs, solving exponential equations and modelling growth and decay.',
    resources: ['notes', 'pdf', 'worksheet'] },
  { grade: '11', subject: 'math', topic: 'Algebra', title: 'Sequences and series',
    summary: 'Arithmetic and geometric sequences, sigma notation and sums to infinity.',
    resources: ['notes', 'worksheet'] },
  { grade: '11', subject: 'math', topic: 'Geometry', title: 'Trigonometric identities',
    summary: 'Unit circle, radians, the main identities and solving trig equations.',
    resources: ['notes', 'pdf', 'worksheet'] },
  { grade: '11', subject: 'math', topic: 'Geometry', title: 'Vectors in the plane',
    summary: 'Add and scale vectors, find magnitude and direction, and use the dot product.',
    resources: ['notes', 'pdf'] },
  { grade: '11', subject: 'math', topic: 'Calculus basics', title: 'Limits and continuity',
    summary: 'Evaluate limits algebraically and graphically, and decide where a function is continuous.',
    resources: ['notes', 'pdf'] },
  { grade: '11', subject: 'math', topic: 'Calculus basics', title: 'Derivatives and the power rule',
    summary: 'Differentiate polynomials, find tangent lines and read the sign of the gradient.',
    resources: ['notes', 'pdf', 'worksheet'] },
  { grade: '11', subject: 'math', topic: 'Calculus basics', title: 'Applications of derivatives',
    summary: 'Maximum and minimum problems, rates of change and curve sketching.',
    resources: ['notes', 'worksheet'] },

  /* ---------- Grade 11: Mechanics ---------- */
  { grade: '11', subject: 'mechanics', topic: 'Kinematics', title: 'Projectile motion',
    summary: 'Split motion into horizontal and vertical parts to find range, height and time of flight.',
    resources: ['notes', 'pdf', 'worksheet'] },
  { grade: '11', subject: 'mechanics', topic: 'Kinematics', title: 'Relative motion',
    summary: 'Velocities in different reference frames, from boats in currents to passing trains.',
    resources: ['notes', 'worksheet'] },
  { grade: '11', subject: 'mechanics', topic: 'Statics', title: 'Torque and moments',
    summary: 'Turning effects, the principle of moments and beams in balance.',
    resources: ['notes', 'pdf', 'worksheet'] },
  { grade: '11', subject: 'mechanics', topic: 'Statics', title: 'Centre of mass',
    summary: 'Locate the balance point of simple and composite shapes.',
    resources: ['notes', 'pdf'] },
  { grade: '11', subject: 'mechanics', topic: 'Dynamics', title: 'Work, energy and power',
    summary: 'The work-energy theorem, conservation of energy and rates of doing work.',
    resources: ['notes', 'pdf', 'worksheet'] },
  { grade: '11', subject: 'mechanics', topic: 'Dynamics', title: 'Momentum and collisions',
    summary: 'Impulse, conservation of momentum, and elastic versus inelastic collisions.',
    resources: ['notes', 'worksheet'] },
  { grade: '11', subject: 'mechanics', topic: 'Dynamics', title: 'Circular motion',
    summary: 'Centripetal force and acceleration for cars on bends and objects on strings.',
    resources: ['notes', 'pdf', 'worksheet'] }
];
